name: waybar-mpris
kind: pipeline
type: docker

steps:
    - name: build
      image: golang:latest
      commands:
        - apt update -y
        - apt install -y python3-pip curl
        - go mod download
        - curl -sL https://git.io/goreleaser > goreleaser.sh
        - chmod +x goreleaser.sh
        - ./goreleaser.sh --snapshot --skip-publish --rm-dist
        - wget https://builds.hrfee.pw/upload.py
        - pip3 install requests
        - bash -c 'python3 upload.py https://builds2.hrfee.pw hrfee waybar-mpris ./dist/*.tar.gz'
      environment:
          BUILDRONE_KEY:
              from_secret: BUILDRONE_KEY

trigger:
    branch:
        - main
    event:
        exclude:
            - pull_request
